name: LUM Sniper Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-lum:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Sniper Script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py

    - name: Commit and Push History
      run: |
        git config --global user.name "LUM Sniper Bot"
        git config --global user.email "bot@github.com"
        git add history.json
        date > keep_alive.txt
        git add keep_alive.txt
        git commit -m "Scansione periodica e keep-alive" || exit 0
        git push
