name: LUM Sniper Bot

on:
  schedule:
    # Esegue ogni 30 minuti
    - cron: '*/30 * * * *'
  workflow_dispatch: # Ti permette di avviarlo a mano se vuoi controllare SUBITO

jobs:
  check-lum:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Sniper Script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        DATE_NOW: $(date +'%d-%m-%Y %H:%M')
      run: python main.py

    - name: Commit and Push History
      # Questo step salva il file history.json se è cambiato
      run: |
        git config --global user.name "LUM Sniper Bot"
        git config --global user.email "bot@github.com"
        git add history.json
        # Il commit fallisce se non ci sono modifiche, quindi usiamo "|| exit 0" per non rompere il workflow
        git commit -m "Aggiornamento storico bandi" || exit 0
        git push
